version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0
    - 15.12.0
    - 15.14.0
    - 15.4.0
    - 15.7.0
    - 15.8.0
  - dependency-name: mongodb
    versions:
    - 3.6.3
    - 3.6.4
    - 3.6.5
  - dependency-name: config
    versions:
    - 3.3.3
    - 3.3.4
  - dependency-name: lodash
    versions:
    - 4.17.20
